name: Zen Twilight Scheduled Releases
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  twilight-release-schedule:
    name: Twilight Release Schedule
    permissions:
      contents: write
    uses: ./.github/workflows/build.yml
    with:
      create_release: true
      update_branch: twilight
      update_version: true

  post-build:
    name: Post Build
    runs-on: ubuntu-latest
    needs: twilight-release-schedule
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js and pnpm
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # TODO: