
on:
  workflow_call:
    inputs:
      build-version:
        description: 'The version to build'
        required: true
        type: string
      profile-data-path-archive:
        description: 'The path to the zip archive containing the profile data'
        required: false
        type: string

jobs:
  windows-profile-build:
    runs-on: windows-latest
    # Script edited from https://github.com/Floorp-Projects/Floorp/blob/ESR115/.github/workflows/window-generate-profile-data-and-jarlog.yml
    steps:
      - name: Clone firefox-source
        run: |
          curl https://archive.mozilla.org/pub/firefox/releases/128.0/source/firefox-128.0.source.tar.xz --output firefox-128.0.source.tar.xz
          7z x firefox-128.0.source.tar.xz
          7z x firefox-128.0.source.tar
          mv firefox-128.0.source firefox-source
          ls
          ls firefox-source

      - uses: actions/download-artifact@v4
        name: Download artifact 
        with:
          path: C:\artifact

      - name:  Unpack artifact
        run: |
          cd C:\artifact
          ls
          7z x ${{ inputs.profile-data-path-archive }}
          ls

      - name: Setup 
        run: |
          (New-Object System.Net.WebClient).DownloadFile("https://ftp.mozilla.org/pub/mozilla/libraries/win32/MozillaBuildSetup-Latest.exe","C:\MozillaBuildSetup-Latest.exe")
          C:\MozillaBuildSetup-Latest.exe /S | out-null

      - name: Generate 
        run: |
          ls
          $Env:USE_MINTTY = "0"

          $workspace_dir = [regex]::replace($env:GITHUB_WORKSPACE, "^([A-Z]):", { "/" + $args.value.Substring(0, 1).toLower() }) -replace "\\","/"
          $workspace_dir = $workspace_dir + "/firefox-source"
          cd $workspace_dir
          echo $workspace_dir

          echo "cd $workspace_dir" '' >> mozilla-build-run.sh
          echo './mach --no-interactive bootstrap --application-choice browser' '' >> mozilla-build-run.sh
          echo 'ls /c/Users/runneradmin/.mozbuild/clang/bin' '' >> mozilla-build-run.sh
          echo 'LLVM_PROFDATA=/c/Users/runneradmin/.mozbuild/clang/bin/llvm-profdata.exe JARLOG_FILE=en-US.log ./mach python build/pgo/profileserver.py --binary /c/artifact/zen/zen.exe' '' >> mozilla-build-run.sh
          C:\mozilla-build\start-shell.bat $workspace_dir\mozilla-build-run.sh

      - name: ğŸ› Debug Session
        if: ${{ failure() }}
        uses: Warpbuilds/gha-debug@v1.3
        timeout-minutes: 15

      - name: Publish merged.profdata
        uses: actions/upload-artifact@v4
        with:
          path: merged.profdata

      - name: Publish en-US.log
        uses: actions/upload-artifact@v4
        with:
          path: en-US.log

